# Generated by Django 4.0.6 on 2022-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('category', models.SmallIntegerField()),
                ('fileType', models.SmallIntegerField()),
                ('fileName', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('ePosta', models.CharField(max_length=255)),
                ('Securityint', models.IntegerField()),
            ],
        ),
    ]
